/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyOperationProduction {
  'id' : bigint,
  'todayProduction' : bigint,
  'date' : string,
  'despatch' : bigint,
  'operationId' : bigint,
}
export interface Operation { 'operationName' : string, 'operationId' : bigint }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateTotalCompleted' : ActorMethod<[bigint, string], bigint>,
  'createDailyProductionReport' : ActorMethod<
    [string, bigint, bigint, bigint],
    bigint
  >,
  'getAllDailyProductionReports' : ActorMethod<
    [],
    Array<DailyOperationProduction>
  >,
  'getAllOperations' : ActorMethod<[], Array<Operation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReportsByOperationAndDateRange' : ActorMethod<
    [bigint, string, string],
    Array<DailyOperationProduction>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDailyProductionReport' : ActorMethod<
    [bigint, string, bigint, bigint],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];