/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DispatchRecord = IDL.Record({
  'destination' : IDL.Text,
  'dispatchDate' : IDL.Text,
  'containerType' : IDL.Text,
  'trackingReference' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const ProductionRecord = IDL.Record({
  'date' : IDL.Text,
  'containerType' : IDL.Text,
  'shift' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DailyProductionReport = IDL.Record({
  'despatched' : IDL.Nat,
  'todayProduction' : IDL.Nat,
  'totalCompleted' : IDL.Nat,
  'date' : IDL.Text,
  'operationName' : IDL.Text,
  'inHand' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const WorkInHandRecord = IDL.Record({
  'currentInventory' : IDL.Nat,
  'containerType' : IDL.Text,
  'dispatchedQuantity' : IDL.Nat,
  'producedQuantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDispatchRecord' : IDL.Func([DispatchRecord], [], []),
  'addProductionRecord' : IDL.Func([ProductionRecord], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDailyProductionReport' : IDL.Func(
      [DailyProductionReport],
      [IDL.Nat],
      [],
    ),
  'deleteDailyProductionReport' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllDailyProductionReports' : IDL.Func(
      [],
      [IDL.Vec(DailyProductionReport)],
      ['query'],
    ),
  'getAllDispatchRecords' : IDL.Func([], [IDL.Vec(DispatchRecord)], ['query']),
  'getAllProductionRecords' : IDL.Func(
      [],
      [IDL.Vec(ProductionRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyProductionReport' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(DailyProductionReport)],
      ['query'],
    ),
  'getProductionRecordsByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ProductionRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkInHandStatus' : IDL.Func([], [IDL.Vec(WorkInHandRecord)], ['query']),
  'initializeDefaultReports' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDailyProductionReport' : IDL.Func(
      [IDL.Nat, DailyProductionReport],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DispatchRecord = IDL.Record({
    'destination' : IDL.Text,
    'dispatchDate' : IDL.Text,
    'containerType' : IDL.Text,
    'trackingReference' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const ProductionRecord = IDL.Record({
    'date' : IDL.Text,
    'containerType' : IDL.Text,
    'shift' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DailyProductionReport = IDL.Record({
    'despatched' : IDL.Nat,
    'todayProduction' : IDL.Nat,
    'totalCompleted' : IDL.Nat,
    'date' : IDL.Text,
    'operationName' : IDL.Text,
    'inHand' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const WorkInHandRecord = IDL.Record({
    'currentInventory' : IDL.Nat,
    'containerType' : IDL.Text,
    'dispatchedQuantity' : IDL.Nat,
    'producedQuantity' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDispatchRecord' : IDL.Func([DispatchRecord], [], []),
    'addProductionRecord' : IDL.Func([ProductionRecord], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDailyProductionReport' : IDL.Func(
        [DailyProductionReport],
        [IDL.Nat],
        [],
      ),
    'deleteDailyProductionReport' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllDailyProductionReports' : IDL.Func(
        [],
        [IDL.Vec(DailyProductionReport)],
        ['query'],
      ),
    'getAllDispatchRecords' : IDL.Func(
        [],
        [IDL.Vec(DispatchRecord)],
        ['query'],
      ),
    'getAllProductionRecords' : IDL.Func(
        [],
        [IDL.Vec(ProductionRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyProductionReport' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(DailyProductionReport)],
        ['query'],
      ),
    'getProductionRecordsByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ProductionRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkInHandStatus' : IDL.Func(
        [],
        [IDL.Vec(WorkInHandRecord)],
        ['query'],
      ),
    'initializeDefaultReports' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDailyProductionReport' : IDL.Func(
        [IDL.Nat, DailyProductionReport],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };