/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyProductionReport {
  'despatched' : bigint,
  'todayProduction' : bigint,
  'totalCompleted' : bigint,
  'date' : string,
  'operationName' : string,
  'inHand' : bigint,
}
export interface DispatchRecord {
  'destination' : string,
  'dispatchDate' : string,
  'containerType' : string,
  'trackingReference' : string,
  'quantity' : bigint,
}
export interface ProductionRecord {
  'date' : string,
  'containerType' : string,
  'shift' : string,
  'notes' : string,
  'quantity' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkInHandRecord {
  'currentInventory' : bigint,
  'containerType' : string,
  'dispatchedQuantity' : bigint,
  'producedQuantity' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDispatchRecord' : ActorMethod<[DispatchRecord], undefined>,
  'addProductionRecord' : ActorMethod<[ProductionRecord], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDailyProductionReport' : ActorMethod<[DailyProductionReport], bigint>,
  'deleteDailyProductionReport' : ActorMethod<[bigint], boolean>,
  'getAllDailyProductionReports' : ActorMethod<
    [],
    Array<DailyProductionReport>
  >,
  'getAllDispatchRecords' : ActorMethod<[], Array<DispatchRecord>>,
  'getAllProductionRecords' : ActorMethod<[], Array<ProductionRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyProductionReport' : ActorMethod<
    [bigint],
    [] | [DailyProductionReport]
  >,
  'getProductionRecordsByDateRange' : ActorMethod<
    [string, string],
    Array<ProductionRecord>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkInHandStatus' : ActorMethod<[], Array<WorkInHandRecord>>,
  'initializeDefaultReports' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDailyProductionReport' : ActorMethod<
    [bigint, DailyProductionReport],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];