/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DailyOperationProduction = IDL.Record({
  'id' : IDL.Nat,
  'todayProduction' : IDL.Nat,
  'date' : IDL.Text,
  'despatch' : IDL.Nat,
  'operationId' : IDL.Nat,
});
export const Operation = IDL.Record({
  'operationName' : IDL.Text,
  'operationId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateTotalCompleted' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createDailyProductionReport' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getAllDailyProductionReports' : IDL.Func(
      [],
      [IDL.Vec(DailyOperationProduction)],
      ['query'],
    ),
  'getAllOperations' : IDL.Func([], [IDL.Vec(Operation)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReportsByOperationAndDateRange' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Vec(DailyOperationProduction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDailyProductionReport' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DailyOperationProduction = IDL.Record({
    'id' : IDL.Nat,
    'todayProduction' : IDL.Nat,
    'date' : IDL.Text,
    'despatch' : IDL.Nat,
    'operationId' : IDL.Nat,
  });
  const Operation = IDL.Record({
    'operationName' : IDL.Text,
    'operationId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateTotalCompleted' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createDailyProductionReport' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAllDailyProductionReports' : IDL.Func(
        [],
        [IDL.Vec(DailyOperationProduction)],
        ['query'],
      ),
    'getAllOperations' : IDL.Func([], [IDL.Vec(Operation)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReportsByOperationAndDateRange' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Vec(DailyOperationProduction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDailyProductionReport' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };